version: '3.1'

services:
  xpostgres:
    image: postgres:10.10
    environment:
      POSTGRES_DB: ics
      POSTGRES_USER: ics
      POSTGRES_PASSWORD: ics
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-logs:/logs
      - ./custom-pg.conf:/etc/postgres.conf
    networks:
      - postgres-net
    restart: always
    command: |
      postgres
      -c logging_collector=on
      -c log_destination=stderr
      -c log_directory=/logs
      -c config_file=/etc/postgres.conf

  xpgadmin:
    image: dpage/pgadmin4
    environment:
      # connect to xpostgres:5432. creds to db from above
      PGADMIN_DEFAULT_EMAIL: ics@ics.com
      PGADMIN_DEFAULT_PASSWORD: ics
    ports:
      - 4000:80
    networks:
      - postgres-net
    depends_on:
      - xpostgres

  xpggis:
    image: mdillon/postgis:10
    environment:
      POSTGRES_DB: ics
      POSTGRES_USER: ics
      POSTGRES_PASSWORD: ics
    ports:
      - 6000:5432
    volumes:
      - ./pggis-data:/var/lib/postgresql/data
    networks:
      - postgres-net

networks:
  postgres-net:
    driver: bridge

